spring:
  application:
    name: gestion-paie-service
server:
  port: 8036
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true